set_property SRC_FILE_INFO {cfile:{C:/Users/T5810/Documents/ONEDRIVE/Documents/Projects/Personal FPGA Projects/Debouncer_VHDL/Debouncer_VHDL.srcs/constrs_1/new/constraints.xdc} rfile:../../../Debouncer_VHDL.srcs/constrs_1/new/constraints.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN E3    IOSTANDARD LVCMOS33 } [get_ports { CLK100MHZ }]; #IO_L12P_T1_MRCC_35 Sch=gclk[100]
set_property src_info {type:XDC file:1 line:34 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN T10   IOSTANDARD LVCMOS33 } [get_ports { output }]; #IO_L24N_T3_A00_D16_14 Sch=led[7]
set_property src_info {type:XDC file:1 line:40 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN B8    IOSTANDARD LVCMOS33 } [get_ports { input }]; #IO_L12P_T1_MRCC_16 Sch=btn[3]
